### ISSUE TITLE
Weapons falling on ground when spawning into the game

### ISSUE THREAD

**Issue by FlamingChilly** [fivem-wl/WeaponOnBack#1]
Hi.
A longstanding issue which I assume you are aware about, is that your weapons which were on your back, falls onto the ground when you spawn into the game.  It can however not be picked up or anything, it's just the props that fall onto the floor.  Is there a way to fix this?

We had this on our non-onesync as well as onesync servers.

**Comment by FlamingChilly** [comment]
You may have a look at this video, around 01:00 - 01:40
https://www.youtube.com/watch?v=nUhNu3bPiVI

**Comment by imckl** [comment]
Yep it is A bug since release, this should be fixed not sonner

**Comment by imckl** [comment]
@FlamingChilly This repo is archived in favor of [weapon-on-back](https://github.com/fivem-wl/future-world/tree/master/projects/weapon-on-back), and this issue has been fixed in new repo.
